AWSTemplateFormatVersion: '2010-09-09'
Description: SPA hosting on S3+CloudFront + Route53 Alias record (uses CloudFront OAI for widest compatibility)

Parameters:
  ProjectName: { Type: String }
  HostedZoneId: { Type: String, Description: "Route53 hosted zone id for the root domain" }
  DomainName:  { Type: String, Description: "sso-poc.example.com" }
  CertificateArn: { Type: String, Description: "ACM cert ARN in us-east-1" }

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${AWS::AccountId}-${AWS::Region}-spa"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${ProjectName} OAI"

  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${ProjectName}-headers"
        SecurityHeadersConfig:
          ContentSecurityPolicy:
            ContentSecurityPolicy: "default-src 'self'; connect-src 'self' https://*.amazoncognito.com; frame-ancestors 'none'; base-uri 'self';"
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Preload: true
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          # Optional (enable later if you want it)
          # XSSProtection:
          #   Protection: true
          #   ModeBlock: true
          #   Override: true

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: [ !Ref DomainName ]
        DefaultRootObject: index.html
        Origins:
          - Id: SpaOrigin
            DomainName: !GetAtt Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: SpaOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6   # AWS Managed: CachingOptimized
        CustomErrorResponses:
          # SPA routing support
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadViaOAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "${Bucket.Arn}/*"

  DnsA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DnsAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  BucketName:      { Value: !Ref Bucket }
  DistributionId:  { Value: !Ref Distribution }
  CloudFrontDomainName: { Value: !GetAtt Distribution.DomainName }
  CloudFrontURL:   { Value: !Sub "https://${DomainName}" }
