AWSTemplateFormatVersion: "2010-09-09"
Description: Cognito UserPool + Hosted UI + Google IdP (PKCE-ready) for the Polylith re-frame project

Parameters:
  ProjectName:
    Type: String
    Description: "Short name used to prefix resources (e.g., aws-login)"

  # Support both localhost and production callback/logout URLs in a single stack.
  CallbackURLs:
    Type: CommaDelimitedList
    Description: "Allowed callback URLs (include /callback). Example: http://localhost:3000/callback,https://app.example.com/callback"

  LogoutURLs:
    Type: CommaDelimitedList
    Description: "Allowed logout URLs (include trailing /). Example: http://localhost:3000/,https://app.example.com/"

  DomainPrefix:
    Type: String
    Description: "Cognito Hosted UI domain prefix (must be globally unique per region/account)."

  # Best-practice for shareable repos: store Google OAuth creds in Secrets Manager.
  #
  # Secret JSON example:
  #   {
  #     "clientId": "....apps.googleusercontent.com",
  #     "clientSecret": "..."
  #   }
  GoogleSecretName:
    Type: String
    Description: "AWS Secrets Manager secret name containing Google OAuth clientId/clientSecret JSON."

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ProjectName}-pool"
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 10
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false

  GoogleProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      AttributeMapping:
        email: email
        given_name: given_name
        family_name: family_name
      ProviderDetails:
        client_id: !Sub "{{resolve:secretsmanager:${GoogleSecretName}:SecretString:client_id}}"
        client_secret: !Sub "{{resolve:secretsmanager:${GoogleSecretName}:SecretString:client_secret}}"

        # IMPORTANT:
        # Google does NOT support an "offline_access" scope value.
        # Cognito will request whatever scopes you set here from Google.
        authorize_scopes: "openid email profile"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleProvider
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${ProjectName}-client"

      # Public SPA client (no client secret)
      GenerateSecret: false

      # Hosted UI settings (PKCE-friendly)
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: [code]              # Authorization Code Flow only
      AllowedOAuthScopes: [openid, email, profile]

      CallbackURLs: !Ref CallbackURLs
      LogoutURLs:   !Ref LogoutURLs
      SupportedIdentityProviders: [COGNITO, Google]

      # Token validity defaults (tweak to taste)
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 7
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

      # Good defaults
      EnableTokenRevocation: true
      PreventUserExistenceErrors: ENABLED

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref DomainPrefix
      UserPoolId: !Ref UserPool
      ManagedLoginVersion: 1

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub "${ProjectName}-UserPoolId"

  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${ProjectName}-UserPoolClientId"

  HostedUiDomain:
    Value: !Sub "https://${DomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
